### ISSUE TITLE
Is it possible to train an encoder for both image and text inputs?

### ISSUE THREAD

**Issue by amirj** [google/seq2seq#105]
I don't know if here is a good place for asking such a questions. Excuse me if its not appropriate.
I just thinking if its possible to train an encoder (recurrent or convolutional) which gets as input both image and text. 
Absolutely possible to train different model for text and image separately but is it possible to train them in a single model?
Any suggestions are welcomed.

**Comment by dennybritz** [comment]
You could have two encoders in the same model, one for images and one for text, and then combine their outputs before feeding them into a decoder, and train them together. That should be easily possible.

If you want the *same* encoder to process both images and text, that's more challenging. I think it might be possible if you can bring both input types into a similar shape and let the encoder learn the difference. I am not sure what the benefit would be though.

**Comment by amirj** [comment]
Thanks for your suggestions.
