### ISSUE TITLE
Illegal Division by Zero 

### ISSUE THREAD

**Issue by tangrui** [google/seq2seq#106]
During training my model, I get a lot of warnings:

```
INFO:tensorflow:Starting evaluation at 2017-03-24-04:29:49
WARNING:tensorflow:multi-bleu.perl script returned non-zero exit code
WARNING:tensorflow:b'Illegal division by zero at /tmp/tmpu0_b8sc7 line 154, <STDIN> line 32.\n'
WARNING:tensorflow:multi-bleu.perl script returned non-zero exit code
WARNING:tensorflow:b'Illegal division by zero at /tmp/tmp7em8bjou line 154, <STDIN> line 64.\n'
WARNING:tensorflow:multi-bleu.perl script returned non-zero exit code
WARNING:tensorflow:b'Illegal division by zero at /tmp/tmp4osfwiwt line 154, <STDIN> line 96.\n'
...
```

Then I use something below to run the prediction, but get a blank file.

```
python -m bin.infer \
  --tasks "
    - class: DecodeText" \
  --model_dir $MODEL_DIR \
  --input_pipeline "
    class: ParallelTextInputPipeline
    params:
      source_files:
        - $DEV_SOURCES" \
  >  ${PRED_DIR}/predictions.txt
```

I'm trying to do text summarization, using the following command:

```
python -m bin.train \
  --config_paths="
      ./example_configs/nmt_medium.yml,
      ./example_configs/train_seq2seq.yml,
      ./example_configs/text_metrics_sp.yml" \
  --model_params "
      vocab_source: $VOCAB_SOURCE
      vocab_target: $VOCAB_TARGET" \
  --input_pipeline_train "
    class: ParallelTextInputPipeline
    params:
      source_files:
        - $TRAIN_SOURCES
      target_files:
        - $TRAIN_TARGETS" \
  --input_pipeline_dev "
    class: ParallelTextInputPipeline
    params:
       source_files:
        - $DEV_SOURCES
       target_files:
        - $DEV_TARGETS" \
  --batch_size 32 \
  --train_steps $TRAIN_STEPS \
  --output_dir $MODEL_DIR
```

I don't know where is wrong, and how to debug.

**Comment by dennybritz** [comment]
> During training my model, I get a lot of warnings

These warning are normal in the early stages of training. The model generates garbage and the `multi-bleu.perl` script will throw an error when there is no overlap between predictions and targets. The warnings should go away once the models starts learning.

> Then I use something below to run the prediction, but get a blank file.

That seems strange. If there is no error, maybe the model is learning to not output an empty sequence?

> I don't know where is wrong, and how to debug.

Look at Tensorbaord and the learning curves. Is the model learning? What is the log perplexity?

**Comment by NonvolatileMemory** [comment]
I have a same problem

**Comment by tangrui** [comment]
Thank you for your reply.

I'll repeat the process and take a look at TensorBoard.

I remember the prediction file isn't that empty, but contains the same line number of the input file, but each line is a blank line.

Does it mean that I should go on training the model with more epochs?

And by the way, I use the large config file, and can get some reasonable result.

**Comment by tangrui** [comment]
I tried the training again and set TRAIN_STEPS from 1000 to 10000, then even use the nmt_small.yml config file, the model can learn.

**Comment by milanv1** [comment]
Hi @tangrui 

Could you point me in the right direction how to add more epochs to train your model? I have only managed to change the nr. of training steps right now.

Thanks in advance.

**Comment by tangrui** [comment]
> I tried the training again and set TRAIN_STEPS from 1000 to 10000, then even use the nmt_small.yml config file, the model can learn.

Just set TRAIN_STEPS environment variable to 10000.

**Comment by KirtiBhandari-Reflektion** [comment]
I have the same issue of blank lines in predictions file. I am using nmt_large config. Besides, is there a way to use only a batch of validation data during eval step?
