### ISSUE TITLE
Coverage penalty

### ISSUE THREAD

**Issue by maxdel** [google/seq2seq#138]
Hi,

is there a way to pass the _coverage penalty_ parameter to the model (or decoder)?

 I found only the length penalty one: 
> inference.beam_search.length_penalty_weight 	 

If no, are there any other ways to adjust coverage related properties?

**Comment by dennybritz** [comment]
No, coverage penalty isn't in the code right now. I played around with it at some point but it didn't seem to help. Also, there are various implementation/types of coverage penalties.
