### ISSUE TITLE
How to train character-level model properly?

### ISSUE THREAD

**Issue by caoyuan** [google/seq2seq#141]
I was trying to train a MT model on char-level, however it seems the model never learned anything meaningful and only produced outputs like the following (for en-de):

`UNK SEQUENCE_END`
`Mit Sicherheit und Gesundheit hat dies wenig zu tun . SEQUENCE_END`

I prepared vocab on char-level and did set "--source_delimiter" and "--target_delimiter" to "". It looks like the pre/post-processing was not properly handled so that words were not split into chars during training, or did I miss anything in the settings?

Below is my command line:
```
python -m bin.train \
       --config_paths="
      ./example_configs/nmt_small.yml,
      ./example_configs/train_seq2seq.yml,
      ./example_configs/text_metrics_sp.yml" \
       --model_params "
      vocab_source: $VOCAB_SOURCE
      vocab_target: $VOCAB_TARGET" \
       --input_pipeline_train "
    class: ParallelTextInputPipeline
    params:
      source_files:
        - $TRAIN_SOURCES
      target_files:
        - $TRAIN_TARGETS
      source_delimiter:
        - \"\"
      target_delimiter:
        - \"\"" \
       --input_pipeline_dev "
    class: ParallelTextInputPipeline
    params:
       source_files:
         - $DEV_SOURCES
       target_files:
         - $DEV_TARGETS
       source_delimiter:
         - \"\"
       target_delimiter:
         - \"\"" \
       --batch_size 32 \
       --train_steps $TRAIN_STEPS \
       --output_dir $MODEL_DIR
```

**Comment by dummyindex** [comment]
--input_pipeline_train "                                                                                                                                                                                                                                                      
    class: ParallelTextInputPipeline                                                                                                                                                                                                                                            
    params:                                                                                                                                                                                                                                                                     
      source_delimiter: ''                                                                                                                                                                                                                                                     
      target_delimiter: ''                                                                                                                                                                                                                                                     
      source_files:                                                                                                                                                                                                                                                             
        - $TRAIN_SOURCES                                                                                                                                                                                                                                                        
      target_files:                                                                                                                                                                                                                                                             
        - $TRAIN_TARGETS" \                                                                                                                                                                                                                                                     
  --input_pipeline_dev "                                                                                                                                                                                                                                                        
    class: ParallelTextInputPipeline                                                                                                                                                                                                                                            
    params:                                                                                                                                                                                                                                                                     
       source_delimiter: ''                                                                                                                                                                                                                                                    
       target_delimiter: ''                                                                                                                                                                                                                                                    
       source_files:                                                                                                                                                                                                                                                            
        - $DEV_SOURCES                                                                                                                                                                                                                                                          
       target_files:                                                                                                                                                                                                                                                            
        - $DEV_TARGETS" \

**Comment by caoyuan** [comment]
Thanks! I should have been more careful in setting the parameters ...

**Comment by shubhamagarwal92** [comment]
Also see #113 for eval parameter

**Comment by amirj** [comment]
@caoyuan What was the problem with your config file?

**Comment by caoyuan** [comment]
@amirj Yes, it should have been just:
params:
  source_delimiter: ''
  target_delimiter: ''

**Comment by sheerun** [comment]
I think this should be documented somewhere, instead of this issue...
