### ISSUE TITLE
Nr. of steps vs. nr. of epochs

### ISSUE THREAD

**Issue by milanv1** [google/seq2seq#146]
I was wondering is there is a way to define the nr. of epochs you want a certain model to run. After reading the tutorial, I am only aware of a way to easily change the nr. of training steps (which isn't the same as training a nr. of epochs, unless I am mistaken).

Thanks in advance

**Comment by M4t1ss** [comment]
Steps in epoch = data size / batch size ?

**Comment by milanv1** [comment]
I know that the nr. of steps to get through your data once (which is what is generally called one epoch, I think) depends on your data size and the batches you are using, but I was just wondering if there was a convenient way in the configurations to let your model train multiple epochs (I remember papers, if I'm not mistaken, where they mention that they train models for x amount of epochs with x amount of training steps per epoch).

**Comment by milanv1** [comment]
http://stackoverflow.com/questions/43319709/tensorflow-nr-of-epochs-vs-nr-of-training-steps/43323546#43323546
