### ISSUE TITLE
How to use trained model in different script?

### ISSUE THREAD

**Issue by MInner** [google/seq2seq#157]
Is there a simple way to load resulting model from python to do inference other then with writing to a temporary files and calling bash scripts? These are `tf.contrib.learn.Estimator`'s, maybe one can do `tf.Saver().restore()` on resulting checkpoints and meta-graphs? Where to look for clues about where to look for that in sources if that is not mentioned somewhere in docs?

**Comment by dennybritz** [comment]
I recommend looking at the `infer.py` script, it loads the model from checkpoints. You can probably adjust the code to your needs.
