### ISSUE TITLE
why concat last context into next input ?

### ISSUE THREAD

**Issue by joyousrabbit** [google/seq2seq#161]
Hello, I understand that we concatenate last output into next input, but why we concatenate also last context into next input? What's the meaning to do this? (I mean, why not last h, or last scores, or nothing, but why last context?)

code here:
next_inputs = tf.concat([next_inputs, outputs.attention_context], 1)

Hope reply please.

**Comment by dennybritz** [comment]
That's the standard approach to implementing attention. Check out "input feeding" section in https://arxiv.org/abs/1508.04025.

**Comment by joyousrabbit** [comment]
@dennybritz , thanks I read the paper that you mentioned. The paper said it's for "alignment decisions should be made jointly taking into account past alignment information." However, the context is a reduce_sum and not contain the alignment information anymore, right? It's the scores who contain the alignment imformation!!! What do you think of it?
