### ISSUE TITLE
seq2seq hogs GPU memory

### ISSUE THREAD

**Issue by rpryzant** [google/seq2seq#163]
seq2seq will reserve all the memory an all the GPU's for a machine, but will only utilize one of them. For example, in the below screenshot only GPU 0 is utilized, but the memory of all three are reserved.

![](http://i.imgur.com/RlJ7fqE.png)

This is the default tensorflow behavior but I still think multi-GPU machines should be managed better.

You could

1) Configure TF to reserve only the memory it needs on a single GPU. This means users could pass a target GPU as a configuration param, and that multiple training runs could be run on the same machine. This can be done with something like 
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.2, allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(device_count={"GPU":0},	gpu_options=gpu_options))
```
or 
```
os.environ['CUDA_VISIBLE_DEVICES'] = '0' # Or whichever device you would like to use
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options, allow_soft_placement=True))
```

2) Do proper single machine, multi-gpu training

**Comment by dennybritz** [comment]
I think the training script already has an option for that: https://github.com/google/seq2seq/blob/master/bin/train.py#L111

I think the reason this is the default behavior of TF is because it makes things faster.
