### ISSUE TITLE
[Feature Request] practical aspects in training NMT models

### ISSUE THREAD

**Issue by amirj** [google/seq2seq#168]
This issue is not directly related to this project, but I want to leverage the knowledge of tf-seq2seq users in training NMT models.
I want to train a seq2seq model (using [nmt_large config file](https://github.com/google/seq2seq/blob/master/example_configs/nmt_large.yml)). I have a 1080 ti (11GB) GPU. The following error is appeared and the learning process is resumed:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Graphics Device
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:03:00.0
Total memory: 10.91GiB
Free memory: 10.75GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Graphics Device, pci bus id: 0000:03:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 10.91G (11715084288 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
```
What does it mean?
I tried to leverage a smaller model (using smaller embedding, units and etc.) but this error is happen again. Does it affect the performance?
**How can I find the proper config (the largest network) that I can handle with my GPU?**
Since users of this projects had a lot of experiments on training NMT models, I suggest to add a page in the documentation to describe the practical aspects of running a NMT model.

**Comment by dennybritz** [comment]
This is a Tensorflow issue and unrelated to this code. Even after printing the error it still trains, right? I've never seen this myself but I saw someone say that you can just ignore the error. If you're really out of memory the program will crash.
