### ISSUE TITLE
BLEU result about nmt_smally.yaml

### ISSUE THREAD

**Issue by apeterswu** [google/seq2seq#169]
Hi,

I've run nmt_small.yaml as your recipe, but the validation BLEU curve is much worse (5 points) than your report on "Tutorial" page https://google.github.io/seq2seq/nmt/, is there anything I should pay attention to?
Other settings are the same as you provided. Thanks very much.

**Comment by dennybritz** [comment]
Yes, the curve in the tutorial is for `nmt_large.yml`. Should make that clear.
