### ISSUE TITLE
Inference on single string

### ISSUE THREAD

**Issue by daphnei** [google/seq2seq#195]
I am looking for the easiest way to pass in a single tokenized input string to a trained model, and having the output string from beam search be returned. 

Is there a way to do inference like this that does not involve reading lines from a file?

My guess is I have to swap out tf.contrib.slim.dataset.Dataset in input_pipeline.py?

**Comment by noname01** [comment]
I was able to put together a hacky solution... It works by passing the string via a feed_dict and using another InferenceTask hook.
https://gist.github.com/noname01/e91e9bea678f0b2f1c9bd283f5b0f452

Is there a better way? I would love to see an API for this.

**Comment by daphnei** [comment]
Thanks a bunch. This is exactly what I was trying to do, although I agree with you it would be nice to have a cleaner way to do it.
