### ISSUE TITLE
how to apply model on validation set periodically during training?

### ISSUE THREAD

**Issue by fritshermans** [google/seq2seq#208]
I would like to apply the model on a separate validation data set at intervals during training. preferrably also watch it on TensorBoard. Does anyone know how to do that?

**Comment by syed-ahmed** [comment]
I think you have to set the `schedule` parameter in the train.py script to `continuous_train_and_eval`. You can also the change the frequency of such evaluation with the `eval_every_n_steps` parameter.

**Comment by fritshermans** [comment]
i've done that but it doesn't lead to a separate plot in TensorBoard with validation errors
