### ISSUE TITLE
How to apply tf_seq2seq on my own data?

### ISSUE THREAD

**Issue by RangoHU** [google/seq2seq#255]
Hello,

I am new to tensorflow and this framework, so I followed the steps in the tutorial. I run the small experiment on the toy-reverse data set. Then I generate  my own dataset, whose vocabulary has 1808 words, and wished to run the seq2seq model on it. But I have the following error:

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1811,128] rhs shape= [23,128]

The format of my own data is exactly the same as those generated by /bin/data/toy.sh. How can I fix this error? Thanks.

**Comment by Zeco-01** [comment]
Try deleting the output dir or select another dir for the new model. As far as I know, the train process will restore the last model, including vocab info and other paramters from previous training, and that may be the cause of the unmatch of data shape.

**Comment by RangoHU** [comment]
@Zeco-01 you are right, thank you soooo much!
