### ISSUE TITLE
Different results during training and inference

### ISSUE THREAD

**Issue by inigo-jauregi** [google/seq2seq#281]
My English-German dataset is divided in train/dev/test. Using train.py I train the model over the train dataset and every 1,000 iterations I evaluate the model over the dev dataset. After 100,000, the BLEU score I can see in tensorboard is **1.56 BLEU**.

After, I use infer.py. I infer the German translations of the English samples in **dev**. I save the translated sentences in German in predictions.txt.

Finally, using multi-bleu.perl, I calculate the BLEU score of the predicted sentences over the ground truth, and my result is **0.93 BLEU**.

Why is not the same as the last value of the evaluation in the training (1.56 BLEU)? I think it should be the same.

**Comment by geert-heyman** [comment]
In the current implementation, no true inference is done during the evaluation phase in train.py. The model uses the groundtruth labels y_1, y_2, ... y_t-1 to predict the next token y_t. When you run infer.py the model uses the previously generated labels (as it should).  See also #214

**Comment by inigo-jauregi** [comment]
Thank you. Very clear.
