### ISSUE TITLE
How to use other type of cell

### ISSUE THREAD

**Issue by afhuertass** [google/seq2seq#286]
Hi !

I would like to know how I can use a cell class defined by me. I have a code based on certain type of RNN , and I had used it with the tensorflow dynamic_rnn( ) , and I wonder what steps had to be taken in order to include this cell inside the seq2seq code so i can use it when specifying the model params ( rnn_cell.cell_class and others ) 

Thanks.

**Comment by geert-heyman** [comment]
You can specify which rnn_cell you want to use in the encoder/decoder in the yaml file that defines your model architecture. Suppose you want to use the nmt_small configuration of the example_configs, then you need to change the value for _cell_class_ from _GRUCell_ to the absolute name of your custom cell class (something like _path.to.custom_cell.module.CustomCell_) [here](https://github.com/google/seq2seq/blob/master/example_configs/nmt_small.yml#L11) and [here](https://github.com/google/seq2seq/blob/master/example_configs/nmt_small.yml#L20).

**Comment by afhuertass** [comment]
Oh Thanks. 

And inside de cell_params I can define all the necessary named parameters to properly build my cell ,right?

**Comment by geert-heyman** [comment]
Yes, indeed.

**Comment by afhuertass** [comment]
Thanks, i think this clarify my doubts. Closing
