### ISSUE TITLE
GPU performance seems quite slow?

### ISSUE THREAD

**Issue by twairball** [google/seq2seq#290]
What am I doing wrong? or is this normal ? 
I'm running this on a paperspace GPU instance (Nvidia Quadro M4000), I can see that TF is running GPU:

````
2017-08-16 23:25:14.571494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro M4000, pci bus id: 0000:00:05.0)
````

But I find that speed compare to CPU on my mac osx is quite slow. **On CPU its about 10~12 secs per 100 steps**. 

training on GPU: 
````
INFO:tensorflow:global_step/sec: 11.8461
INFO:tensorflow:loss = 0.429633, step = 4102 (8.440 sec)
INFO:tensorflow:global_step/sec: 12.5811
INFO:tensorflow:loss = 1.15494, step = 4202 (7.949 sec)
INFO:tensorflow:global_step/sec: 12.8112
INFO:tensorflow:loss = 0.618732, step = 4302 (7.805 sec)
INFO:tensorflow:global_step/sec: 12.6669
INFO:tensorflow:loss = 0.431998, step = 4402 (7.895 sec)
INFO:tensorflow:global_step/sec: 12.5604
INFO:tensorflow:loss = 0.413903, step = 4502 (7.961 sec)
INFO:tensorflow:global_step/sec: 12.6163
INFO:tensorflow:loss = 0.96644, step = 4602 (7.926 sec)
INFO:tensorflow:global_step/sec: 12.7082
INFO:tensorflow:loss = 0.566871, step = 4702 (7.869 sec)
INFO:tensorflow:global_step/sec: 12.6497
INFO:tensorflow:loss = 0.401508, step = 4802 (7.905 sec)
INFO:tensorflow:global_step/sec: 12.751
INFO:tensorflow:loss = 0.635681, step = 4902 (7.843 sec)
INFO:tensorflow:Saving checkpoints for 5001 into /tmp/nmt_tutorial/model.ckpt.
INFO:tensorflow:Loss for final step: 0.722824.
INFO:tensorflow:Evaluating model now.
INFO:tensorflow:Creating AttentionSeq2Seq in mode=eval
````

**Comment by davidpham87** [comment]
On the output that you show us, you do 12 steps per second, that is 0.08 second per steps, which is around 120 faster than your CPU.

**Comment by twairball** [comment]
Sorry i edited my orig post, should be 10~12 secs per 100 steps, I was referring to the time measurement in parentheses.

**Comment by davidpham87** [comment]
Did you check the nvidia-smi command to observe gpu-utilization?

**Comment by twairball** [comment]
It looked normal, I will try running the experiment on a new GPU instance.

@davidpham87 what performance do you typically see for NMT training?

**Comment by davidpham87** [comment]
It depends on so many parameters. I used a vocabulary of 15k words, 128 hidden units for encoder decoder and attention and get around 5 steps/second on a 1080Ti.

**Comment by twairball** [comment]
thanks for the reference!
