### ISSUE TITLE
Is there any built-in config for limiting GPU usage?

### ISSUE THREAD

**Issue by ptresende** [google/seq2seq#298]
TF supports this out-of-the-box with
```
import tensorflow as tf

config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.45
```

Does seq2seq have any build-in config file where this parameter can be specified?

**Comment by jorgetravieso** [comment]
@ptresende It's the gpu_memory_fraction FLAG in bin/train.py, default to 1.0

**Comment by ptresende** [comment]
Thanks @jtraviesor
