### ISSUE TITLE
Correcting Un-PEP263 encoding definition

### ISSUE THREAD

**Issue by alvations** [google/seq2seq#35]
[Un-PEP263-like](https://www.python.org/dev/peps/pep-0263/#defining-the-encoding) style of encoding definitions should be corrected. The python script's encoding should be magically declared in the 1st/2nd line otherwise it'll not be useful and be treated as a normal comment.

Maybe it should follow how TF's style where the encoding definition comes the license/copyrights, e.g. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/lib/python/http_util_test.py

For details, see http://stackoverflow.com/q/42777847/610569

**Comment by dennybritz** [comment]
Oh, this is good, I had no idea. Will fix :)
