### ISSUE TITLE
Whether to add the funtion of attention mechanism?

### ISSUE THREAD

**Issue by tangzhenyu** [google/seq2seq#36]
I cannot find some traces of attention mechanism,and I am curious about whether have added the funtion of attention mechanism in this seq2seq model framework.

**Comment by dennybritz** [comment]
The attention mechanism is defined in [`attention.py`](https://github.com/google/seq2seq/blob/master/seq2seq/decoders/attention.py), and it works together with `attention_decoder.py`.

You can add your own attention mechanism if you inherit from `AttentionLayer`

**Comment by tangzhenyu** [comment]
Yes,it is what I want to know,thanks,dennybritz ~
Is there some documents or instructions about how to generate the attention matrix when decode a sentence?

**Comment by dennybritz** [comment]
Yes, see [Visualizing Attention](https://google.github.io/seq2seq/inference/#visualizing-attention). This will generate a matrix like this:

![00007](https://cloud.githubusercontent.com/assets/403133/23886948/ec0ac97c-083b-11e7-83d9-75b752c6fdb2.png)

It also writes the raw scores to disk.

**Comment by tangzhenyu** [comment]
I found that when I go to url  "https://google.github.io/seq2seq/inference/  "I can find some useful functions when decode a sentence,like visualizing attention,dumping beams~
It'a very useful tool~
I think I can completely move my job to this platform~

**Comment by tangzhenyu** [comment]
thanks again~dennybritz
