### ISSUE TITLE
ImportError: cannot import name contrib

### ISSUE THREAD

**Issue by tangzhenyu** [google/seq2seq#37]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "seq2seq/__init__.py", line 24, in <module>
    from seq2seq import contrib
ImportError: cannot import name contrib
When I run"python -m unittest seq2seq.test.pipeline_test",I got this error.Could someone tell me how to solve this problem?

**Comment by tangzhenyu** [comment]
Is this framework not support the version of tensorflow0.12.1?

**Comment by dennybritz** [comment]
Yes, you need Tensorflow 1.0.

**Comment by tangzhenyu** [comment]
alright,thanks

**Comment by sheerun** [comment]
I get the same error for tensorflow 1.2.1

**Comment by shawnnylxx** [comment]
same error in tensorflow 1.2.1
it is OK when downgrade to tensorflow 1.0.1

**Comment by David-Levinthal** [comment]
broken in R1.3rc0

**Comment by David-Levinthal** [comment]
I believe this can be fixed by modifying seq2seq/seq2seq/contrib/seq2seq/helper.py per the instructions in:
https://github.com/google/seq2seq/pull/254/files

#from tensorflow.contrib.distributions.python.ops import bernoulli
#from tensorflow.contrib.distributions.python.ops import categorical
try:
  from tensorflow.python.ops.distributions import bernoulli
  from tensorflow.python.ops.distributions import categorical
except:
  from tensorflow.contrib.distributions.python.ops import bernoulli
  from tensorflow.contrib.distributions.python.ops import categorical
seems to work for me now with 1.3 rc0 and R1.2

**Comment by wandabwa2004** [comment]
@David-Levinthal  is right.  Just replace these lines in seq2seq/helper.py:

from tensorflow.contrib.distributions.python.ops import bernoulli
from tensorflow.contrib.distributions.python.ops import categorical

with these:

from tensorflow.python.ops.distributions import bernoulli
from tensorflow.python.ops.distributions import categorical

I'm running tensorflow 1.2

**Comment by jhancock1975** [comment]
I just ran into the same thing using tensorflow 1.3.0.  Should I create a pull request, or has someone already created one?

**Comment by chenchiwei** [comment]
I got the same problem in tensorflow 1.4.1

**Comment by NajeebTyson** [comment]
same problem with tensorflow 1.5.0

**Comment by enockipp** [comment]
same problem with tf 1.5.0
