### ISSUE TITLE
WMT 2016 En-De Download Link is broken

### ISSUE THREAD

**Issue by hemingkx** [google/seq2seq#379]
Hi,
the WMT'2016 en-de download link you provided before [seq2seq page](https://google.github.io/seq2seq/data/) is broken now, which is:
https://drive.google.com/open?id=0B_bZck-ksdkpM25jRUN2X2UxMm8

Appreciate it very much if you can update the link, thanks!

**Comment by zhanchey** [comment]
same question, please help!
