### ISSUE TITLE
When metric_fn are called references starts with SEQUENCE_START and hypothesis does not.

### ISSUE THREAD

**Issue by rasmusbergpalm** [google/seq2seq#39]
This makes a simple accuracy metric that checks hyp==ref break

I dunno if this is intended, but at least to me it was a surprise.

Thanks for the great lib btw.

**Comment by dennybritz** [comment]
Thanks for reporting. The right thing to do is probably to append/prepend `SEQUENCE_START` and`SEQUENCE_END` in the model and remove it from both labels and predictions when calling the metric function. Will need to take look at this.

**Comment by dennybritz** [comment]
Should be fixed in #72
