### ISSUE TITLE
why there is always error "ValueError: Input Pipeline definition must have a class property."

### ISSUE THREAD

**Issue by DaoD** [google/seq2seq#40]
here is my config.yml

model: BasicSeq2Seq
model_params:
  bridge.class: seq2seq.models.bridges.InitialStateBridge
  embedding.dim: 1024
  encoder.class: seq2seq.encoders.UnidirectionalRNNEncoder
  encoder.params:
    rnn_cell:
      cell_class: BasicLSTMCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 1
  decoder.class: seq2seq.decoders.BasicDecoder
  decoder.params:
    rnn_cell:
      cell_class: BasicLSTMCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 1
  optimizer.name: Adam
  optimizer.learning_rate: 0.0001
  source.max_seq_len: 83
  source.reverse: false
  target.max_seq_len: 95
  vocab_source: ./data/vocab_post_50000
  vocab_target: ./data/vocab_comt_50000
input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files: ['./data/post_50000']
    target_files: ['./data/comt_50000']
batch_size: 64
train_steps: 1000
output_dir: ./model/50000

when I use the command below to run the model and there is always an error: "ValueError: Input Pipeline definition must have a class property"
python3 -m bin.train --config_paths="./myconfig/config_50000.yml,./myconfig/train_seq2seq.yml"

**Comment by dennybritz** [comment]
I think the problem here is that you are not passing the `input_pipeline_dev` argument, which is required. Ideally you should always have a validation set ;)

It's probably a good idea to throw a better error message and to make the development data optional. Will do that.

Thanks for reporting.

**Comment by dennybritz** [comment]
Unfortunately the Tensorflow `Experiment` class does not allow you to disable evaluation, so you need to pass an `input_pipeline_dev`. I at least updated the code to throw a better error message though.

**Comment by DaoD** [comment]
Thanks for your kindly reply! @dennybritz

**Comment by guotong1988** [comment]
Same problem. Thank you.

**Comment by Sammyreus** [comment]
@dennybritz  i am having the same problem but i am using both dev data as well as train set. 
**_config.yml_**
`model: AttentionSeq2seq
model params:
   vocab_source: ${HOME}/nil/beam/seq2seq/tmp/vocab.50k.bpe.32000.en
   vocab_target: ${HOME}/nil/beam/seq2seq/tmp/vocab.50k.bpe.32000.hi
   input_pipeline_train:
   input_pipeline_train:
    class: ParallelTextInputPipeline
    params:
       - source_files: ${HOME}/nil/beam/seq2seq/tmp/test.bpe.32000.en
       - target_files: ${HOME}/nil/beam/seq2seq/tmp/test.bpe.32000.hi
  input_pipeline_dev:
    class: ParallelTextInputPipeline
    params:
       - source_files: ${HOME}/nil/beam/seq2seq/tmp/IITB.en-hi.bpe.32000.en
       - target_files: ${HOME}/nil/beam/seq2seq/tmp/IITB.en-hi.bpe.32000.hi
  train_steps: ${HOME}/nil/beam/seq2seq/tmp/train
  output_dir: ${HOME}/nil/beam/seq2seq/tmp/model
'

**_beam.yml_**
model: AttentionSeq2Seq
model_params:
  attention.class: seq2seq.decoders.attention.AttentionLayerBahdanau
  attention.params:
    num_units: 512
  bridge.class: seq2seq.models.bridges.ZeroBridge
  embedding.dim: 512
  encoder.class: seq2seq.encoders.BidirectionalRNNEncoder
  encoder.params:
    rnn_cell:
      cell_class: GRUCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 2
  decoder.class: seq2seq.decoders.BeamSearchDecoder
  decoder.params:
    rnn_cell:
      cell_class: GRUCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 2
  optimizer.name: Adam
  optimizer.params:
    epsilon: 0.0000008
  optimizer.learning_rate: 0.0001
  source.max_seq_len: 50
  source.reverse: false
  target.max_seq_len: 50


training the set: python -m bin.train  --config_paths="./example_configs/beam.yml,example_configs/train_seq2seq.yml,./config.yml"
