### ISSUE TITLE
find an error when run command:python -m unittest seq2seq.test.pipeline_test

### ISSUE THREAD

**Issue by victorustc** [google/seq2seq#42]
~/desktop/code/python_program/seq2seq$ python -m unittest seq2seq.test.pipeline_test
.E
======================================================================
ERROR: test_train_infer (seq2seq.test.pipeline_test.PipelineTest)
Tests training and inference scripts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "seq2seq/test/pipeline_test.py", line 78, in test_train_infer
    os.path.join(BIN_FOLDER, "train.py"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)

----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (errors=1)

**Comment by dennybritz** [comment]
Hm. Unicode errors are the worst since I have no way of replicating them. Can you share details about your Python version and your OS? Are you using virtualenv?

**Comment by victorustc** [comment]
@dennybritz python version:2.7, OS:ubuntu 16.10, without using virtualenv.
Thank you !

**Comment by Codelegant92** [comment]
@victorustc Maybe you can change python version to 3.5. I met the same error when using anaconda - python2.7 in Mac OSX.

**Comment by victorustc** [comment]
@dennybritz how I can fix it?

**Comment by manene** [comment]
have u fixed it ? @victorustc

**Comment by brightmart** [comment]
if you are using python 2.7, add below three lines, can fix this problem:
import sys
reload(sys)
sys.setdefaultencoding( "utf-8" )

**Comment by dennybritz** [comment]
Sorry, I'm not sure what the problem here could be. I added some more unicode check in the latest version, let me know if the problem still exists after pulling the latest update. I'm closing this for now. If you still have the problem please re-open.

**Comment by Sammyreus** [comment]
Still causing the same problem:------

>  python -m unittest seq2seq.test.pipeline_test
WARNING:tensorflow:From /home/nil/seq2seq/seq2seq/test/pipeline_test.py:57: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
.E
======================================================================
ERROR: test_train_infer (seq2seq.test.pipeline_test.PipelineTest)
Tests training and inference scripts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nil/seq2seq/seq2seq/test/pipeline_test.py", line 76, in test_train_infer
    _clear_flags()
  File "/home/nil/seq2seq/seq2seq/test/pipeline_test.py", line 44, in _clear_flags
    tf.app.flags.FLAGS = tf.app.flags._FlagValues()
AttributeError: module 'tensorflow.python.platform.flags' has no attribute '_FlagValues'

----------------------------------------------------------------------
Ran 2 tests in 0.134s

**Comment by prp20** [comment]
Yes, Just tried to run the same code as above but ran into similar problems as mentioned  by @Sammyreus

**Comment by fooSynaptic** [comment]
still cannot pass the test similar with the problem of @Sammyreus
