### ISSUE TITLE
Error in 'python': double free or corruption (!prev)

### ISSUE THREAD

**Issue by Codelegant92** [google/seq2seq#62]
I was playing with the toy data and this error appeared when I ran the 'Decoding with Beam Search' script. What's the probable reason and how can I fix it? Thank you.

**Comment by Codelegant92** [comment]
Ubuntu 14.04, anaconda, python3.6, tensorflow-1.0.1

**Comment by dennybritz** [comment]
Probably Tensorflow issue, not related to this code: https://github.com/tensorflow/tensorflow/issues/6968

I'll close this for now. Please open again if you think it's an issue in this code.
