### ISSUE TITLE
Error in test_train_infer

### ISSUE THREAD

**Issue by Akiiino** [google/seq2seq#64]
So, I have cloned the repo and am trying to start using it. As a sensible first step I decided to run the provided test, only to be greeted with this:

http://pastebin.com/9XBrTb7m

I tried reinstalling all I could, and I am pretty sure all other required pieces are as up-to-date as they could ever be and are functioning properly. I am using OS X 10.12 and/or 10.11 --- the error is present in both.

What could be the source of this and will it hinder my ability to use the software?

**Comment by dennybritz** [comment]
What Python version are you using?

**Comment by Akiiino** [comment]
```
akiiinos-MBP:seq2seq akiiino$ python3 -V
Python 3.6.0
```

**Comment by dennybritz** [comment]
Thanks, it's a unicode error that's related to the Python version. We're testing with Python 3.5 and 2.7 and haven't seen it. I'll make sure it works with 3.6, but it may take a day or so.

**Comment by dennybritz** [comment]
This may fix it #65 

Please try again with the latest version and let me know if the error still exists.

**Comment by Akiiino** [comment]
Yes, that did fix it, thank you!
