### ISSUE TITLE
Error from the simple pipeline unit test

### ISSUE THREAD

**Issue by kyleyeung** [google/seq2seq#84]
When I was executing
```bash
python -m unittest seq2seq.test.pipeline_test
```
there was an a error and following is the log:
```bash
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 5705 get requests, put_count=5553 evicted_count=1000 eviction_rate=0.180083 and unsatisfied allocation rate=0.219457
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:Performing full trace on next step.
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcupti.so.8.0. LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/lib64:
F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:59] Check failed: ::tensorflow::Status::OK() == (::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f)) (OK vs. Not found: /home/dl/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks)could not find cuptiActivityRegisterCallbacksin libcupti DSO
```
There's a fatal in the last line and I'm not sure how to fix this. This bug appeared only after I have git pulled the repository today, some version in the last week worked fine. Can someone please help?

Ubuntu 14.04, Cuda 8.0

**Comment by dennybritz** [comment]
This seems like a Tensorflow issue, not related to this code. Please open an issue in the Tensorflow repository: https://github.com/tensorflow/tensorflow/issues

**Comment by brightmart** [comment]
below fix will solve the problem: 
"seems that you need to add /usr/local/cuda-8.0/extras/CUPTI/lib64 to LD_LIBRARY, solved it".
for more detail, check this link: https://github.com/tensorflow/tensorflow/issues/7110

**Comment by kyleyeung** [comment]
@brightmart  Yeah, that exactly worked. This is a silly mistake. Thanks so much!
