### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by syed-ahmed** [google/seq2seq#92]
Are there any plans on putting an option for data augmentation (similar to im2txt) in the input pipeline?

**Comment by dennybritz** [comment]
That's a good idea. What kind of data augmentation strategies were you thinking about? I'll tag this a feature.

**Comment by syed-ahmed** [comment]
I think the implementation in im2txt (https://github.com/tensorflow/models/blob/master/im2txt/im2txt/ops/image_processing.py#L39) is pretty neat. They spin up 4 threads to randomly flip and modify brightness, saturation, hue and contrast of an image. Having such a mechanism in seq2seq might be beneficial.

**Comment by dennybritz** [comment]
Oh I see, you mean for images. The image input pipeline and image captioning model is still very experimental, but I'm definitely planning to add data augmentation to that.

**Comment by webmaven** [comment]
One possibility for augmentation of text datasets is to generate typos, misspellings, regional spelling variants, colloquialisms, word substitutions, and the like.

In theory, this would make the translations more robust in the face of human input, at the cost of expanding the data significantly.

**Comment by syed-ahmed** [comment]
Another possibility for naturally augmenting seq2seq for machine translation could be curriculum training (from lip reading sentences in the wild: https://arxiv.org/pdf/1611.05358.pdf).
