### ISSUE TITLE
Couldn't open CUDA library libcupti.so.8.0. LD_LIBRARY_PATH: /usr/local/cudnn/lib64:/usr/local/cudnn/include:/usr/local/cuda-8.0/lib64

### ISSUE THREAD

**Issue by brightmart** [google/seq2seq#97]
we can use tensorflow GPU version without problem in other model. but when running below command, 
it have above error. and we are sure that LD_LIBRARY_PATH is available, and can be used in other model.
this may related to the 'path' problem when running the command.
--------------------------------------------------------------
python -m bin.train \
  --config_paths="
      ./example_configs/nmt_small.yml,
      ./example_configs/train_seq2seq.yml,
      ./example_configs/text_metrics_bpe.yml" \
  --model_params "
      vocab_source: $VOCAB_SOURCE
      vocab_target: $VOCAB_TARGET" \
  --input_pipeline_train "
    class: ParallelTextInputPipeline
    params:
      source_files:
        - $TRAIN_SOURCES
      target_files:
        - $TRAIN_TARGETS" \
  --input_pipeline_dev "
    class: ParallelTextInputPipeline
    params:
       source_files:
        - $DEV_SOURCES
       target_files:
        - $DEV_TARGETS" \
  --batch_size 32 \
  --train_steps $TRAIN_STEPS \
  --output_dir $MODEL_DIR

Couldn't open CUDA library libcupti.so.8.0. LD_LIBRARY_PATH: /usr/local/cudnn/lib64:/usr/local/cudnn/include:/usr/local/cuda-8.0/lib64

**Comment by brightmart** [comment]
below fix will solve the problem:
"seems that you need to add /usr/local/cuda-8.0/extras/CUPTI/lib64 to LD_LIBRARY, solved it".
for more detail, check this link: tensorflow/tensorflow#7110

**Comment by NonvolatileMemory** [comment]
if you use ubuntu you should use the bash" export" to modiffiy your local path

**Comment by shatu** [comment]
Thanks @brightmart .. Just wondering if doing so globally will have any impact on other perfectly working TF projects?

**Comment by prabhuiitdhn** [comment]
check below link for solution:
https://github.com/tensorflow/tensorflow/issues/8830#issuecomment-466278476

It worked for me, I hope this will work fine for you. if not, Please feel free to connect.
