### ISSUE TITLE
 ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by NonvolatileMemory** [google/seq2seq#99]
Hello,I am an outdoor man of this scope.So my question may be very stupid.sorry^-^
I use the model to train a chatbot.But I have an error:
line 174, in rouge_n
    recall = overlapping_count / reference_count
ZeroDivisionError: division by zero

why I get this?

ps:formation of the file to endoce,decode is UTF-8.

**Comment by dennybritz** [comment]
I think this was fixed in https://github.com/google/seq2seq/pull/94 - Please pull the latest version.

**Comment by NonvolatileMemory** [comment]
Thanks,but I use the latest version but I have an another bug:
WARNING:tensorflow:multi-bleu.perl script returned non-zero exit code
WARNING:tensorflow:b'Illegal division by zero at /tmp/tmpyjco9aw8 line 154, <STDIN> line 24512.\n'

I run this program in ubuntu terminal and it just show as above,always warning.
P.S:
if I change the YAML of text_metrics_bpe.yml the eva will not go on.Can you explain the configuration of this yaml.Thanks very lot!
